name: Publish image in Docker Hub on release

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (production)
        run: |
          TAG=${{ github.event.release.tag_name }}
          IMAGE=${{ secrets.DOCKER_USER }}/trackhub-1

          echo "Building production image $IMAGE:$TAG ..."
          docker build -t $IMAGE:$TAG -t $IMAGE:latest -f docker/images/Dockerfile.selfhosted .
          docker push $IMAGE --all-tags
