name: Publish image in Docker Hub on trunk changes

on:
  push:
    branches: [trunk]
  workflow_dispatch:

jobs:
  push_to_registry:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (staging)
        run: |
          TAG=${{ github.sha }}
          IMAGE=${{ secrets.DOCKER_USER }}/trackhub-1-staging

          echo "Building image with tag $TAG ..."
          docker build -t $IMAGE:$TAG -t $IMAGE:latest -f docker/images/Dockerfile.selfhosted .
          docker push $IMAGE --all-tags
