name: Deploy TrackHub to Proxmox (self-hosted)

on:
  push:
    branches:
      - trunk
      - main
  workflow_dispatch:

jobs:
  deploy-pre:
    if: github.ref_name == 'trunk'
    name: Deploy Pre (self-hosted)
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build selfhosted image for pre
        run: |
          docker build \
            -f docker/images/Dockerfile.selfhosted \
            -t trackhub-selfhosted:trunk .

      - name: Deploy pre container
        run: |
          docker rm -f trackhub-pre || true

          docker run -d \
            --name trackhub-pre \
            -p 5001:5000 \
            --env-file /home/pabolimor/trackhub-pre.env \
            -v /etc/mysql/ssl/ca.pem:/etc/ssl/certs/mariadb-ca.pem:ro \
            --add-host=host.docker.internal:host-gateway \
            --restart always \
            trackhub-selfhosted:trunk

  deploy-prod:
    if: github.ref_name == 'main'
    name: Deploy Prod (self-hosted)
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build selfhosted image for prod
        run: |
          docker build \
            -f docker/images/Dockerfile.selfhosted \
            -t trackhub-selfhosted:${{ github.sha }} .

      - name: Deploy prod container
        run: |
          docker rm -f trackhub-prod || true

          docker run -d \
            --name trackhub-prod \
            -p 5002:5000 \
            --env-file /home/pabolimor/trackhub-prod.env \
            -v /etc/mysql/ssl/ca.pem:/etc/ssl/certs/mariadb-ca.pem:ro \
            --add-host=host.docker.internal:host-gateway \
            --restart always \
            trackhub-selfhosted:${{ github.sha }}
